version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/bindings/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/bindings/rust"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/bindings/go"
    schedule:
      interval: "weekly"
